- id: check-line-length
  name: check-line-length
  entry: cathaysia-line-length
  language: python
  files: \.(rs|ts|tsx)$

- id: ast-grep-rules
  name: ast-grep-rules
  entry: cathaysia-ast-grep
  language: python
  additional_dependencies:
    - ast-grep-cli==0.44.0
  files: \.rs$

- id: move-module-mod
  name: move-module-mod
  entry: cathaysia-move-module
  language: python
  files: \.rs$

- id: compact_workspace_deps
  name: compact_workspace_deps
  entry: cathaysia-compact-workspace-deps
  language: python
  files: (^|/)Cargo\.toml$

- id: full-qualify-log
  name: full-qualify-log
  entry: cathaysia-qualify-tracing-macros
  language: python
  files: \.rs$
  pass_filenames: false
